#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE storeit;
    GRANT ALL PRIVILEGES ON DATABASE storeit TO $POSTGRES_USER;
    CREATE DATABASE eventit;
    GRANT ALL PRIVILEGES ON DATABASE eventit TO $POSTGRES_USER;
EOSQL
